# Generated by Django 5.2 on 2025-06-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='mode',
        ),
    ]
