# Generated by Django 5.2 on 2025-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_uploadedfile_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_script',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
