# Generated by Django 5.2 on 2025-06-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_uploadedfile_processed_script_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcesssedScript',
            new_name='ProcessedScript',
        ),
    ]
