# Generated by Django 5.2 on 2025-07-03 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_plan', models.CharField(blank=True, choices=[('one_off', 'One Off'), ('starter', 'Starter'), ('pro', 'Pro'), ('studio', 'Studio')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
