# Generated by Django 5.2 on 2025-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_monthlyscriptquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='scripts_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MonthlyScriptQuota',
        ),
    ]
