# Generated by Django 5.2 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_usersubscription_scripts_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='audio_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
