# Generated by Django 5.2 on 2025-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_usersubscription_audio_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedscript',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
