# Generated by Django 5.2 on 2025-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_processedscript_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
